
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { ItemEx, GqlItemEx } from './_.Sitecore.Override'
// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { ComponentProps } from '../lib/component-props';
// @ts-ignore 
import { SiteSettings as FeatureBlueYonderSiteSettings } from "./Feature.BlueYonder.model"
// @ts-ignore 
import { BaseComponents as FeatureBlueYonderBaseComponents } from "./Feature.BlueYonder.model"
// @ts-ignore 
import { BaseFields as FoundationBlueYonderBaseFields } from "./Foundation.BlueYonder.model"

export namespace BaseComponents.Footer {

    /**
    * Represents the template /sitecore/templates/Feature/blueyonder/Base Components/Footer/Footer
    */
    export type Footer = FoundationBlueYonderBaseFields.Logo &  {
        fields?: { 
            /**
            * Represents the Contact Title field (7f3dbb4d-073b-4bad-92db-b1f64e5b648b).
            */
            contactTitle?: Field<string>;

            /**
            * Represents the Copyright Text field (f25aa45e-3eb8-4f6a-873e-df369fb31ba9).
            */
            copyRightText?: Field<string>;

            /**
            * Represents the General Links field (dca3aacb-f281-433e-a87c-3a7df429930c).
            */
            generalLinks?: Item[];

            /**
            * Represents the Legal Links field (b056d402-6345-4a44-8d23-e424a1e7947a).
            */
            legalLinks?: Item[];

            /**
            * Represents the Phone Number field (2a244a8a-7efd-4035-b3be-da2df1a8fb03).
            */
            phoneNumber?: LinkField;

            /**
            * Represents the Social Links field (d24cd667-d512-4d70-9532-425fed21b2ee).
            */
            socialLinks?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/blueyonder/Base Components/Footer/Footer
    */
    export type FooterJson = FoundationBlueYonderBaseFields.LogoJson &  {
        
            /**
            * Represents the Contact Title field (7f3dbb4d-073b-4bad-92db-b1f64e5b648b).
            */
            contactTitle?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Copyright Text field (f25aa45e-3eb8-4f6a-873e-df369fb31ba9).
            */
            copyRightText?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the General Links field (dca3aacb-f281-433e-a87c-3a7df429930c).
            */
            generalLinks?: {
                targetItems: any[]
            };

            /**
            * Represents the Legal Links field (b056d402-6345-4a44-8d23-e424a1e7947a).
            */
            legalLinks?: {
                targetItems: any[]
            };

            /**
            * Represents the Phone Number field (2a244a8a-7efd-4035-b3be-da2df1a8fb03).
            */
            phoneNumber?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Social Links field (d24cd667-d512-4d70-9532-425fed21b2ee).
            */
            socialLinks?: {
                targetItems: any[]
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/blueyonder/Base Components/Footer/Footer Folder
    */
    export type FooterFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/blueyonder/Base Components/Footer/Footer Folder
    */
    export type FooterFolderJson =  {
        

    }
}
export namespace BaseComponents {

    /**
    * Represents the template /sitecore/templates/Feature/blueyonder/Base Components/Header
    */
    export type Header =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/blueyonder/Base Components/Header
    */
    export type HeaderJson =  {
        

    }
}
export namespace BaseComponents.Navigation {

    /**
    * Represents the template /sitecore/templates/Feature/blueyonder/Base Components/Navigation/Link
    */
    export type Link = FoundationBlueYonderBaseFields.Cta &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/blueyonder/Base Components/Navigation/Link
    */
    export type LinkJson = FoundationBlueYonderBaseFields.CtaJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/blueyonder/Base Components/Navigation/Link Folder
    */
    export type LinkFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/blueyonder/Base Components/Navigation/Link Folder
    */
    export type LinkFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/blueyonder/Base Components/Navigation/Primary Footer Navigation
    */
    export type PrimaryFooterNavigation = FoundationBlueYonderBaseFields.PrimaryNavigation &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/blueyonder/Base Components/Navigation/Primary Footer Navigation
    */
    export type PrimaryFooterNavigationJson = FoundationBlueYonderBaseFields.PrimaryNavigationJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/blueyonder/Base Components/Navigation/Secondary Navigation
    */
    export type SecondaryNavigation =  {
        fields?: { 
            /**
            * Represents the Navigation Link field (f6267b83-8592-43ae-b05c-1da8a07e94e2).
            */
            navigationLink?: LinkField;

            /**
            * Represents the Navigation Title field (27a8e854-6655-4c54-8b41-5e1368517300).
            */
            navigationTitle?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/blueyonder/Base Components/Navigation/Secondary Navigation
    */
    export type SecondaryNavigationJson =  {
        
            /**
            * Represents the Navigation Link field (f6267b83-8592-43ae-b05c-1da8a07e94e2).
            */
            navigationLink?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Navigation Title field (27a8e854-6655-4c54-8b41-5e1368517300).
            */
            navigationTitle?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/blueyonder/Base Components/Navigation/Social Link
    */
    export type SocialLink =  {
        fields?: { 
            /**
            * Represents the Social Icon field (c25059bb-c0a9-4e81-adde-3d54cf2c2504).
            */
            socialIcon?: ImageField;

            /**
            * Represents the Social Url field (dbf74438-326f-4624-9b56-54978cb20fe6).
            */
            socialUrl?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/blueyonder/Base Components/Navigation/Social Link
    */
    export type SocialLinkJson =  {
        
            /**
            * Represents the Social Icon field (c25059bb-c0a9-4e81-adde-3d54cf2c2504).
            */
            socialIcon?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Social Url field (dbf74438-326f-4624-9b56-54978cb20fe6).
            */
            socialUrl?: {
                jsonValue: LinkField
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/blueyonder/Base Components/Navigation/Social Link Folder
    */
    export type SocialLinkFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/blueyonder/Base Components/Navigation/Social Link Folder
    */
    export type SocialLinkFolderJson =  {
        

    }
}
export namespace BaseComponents.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/blueyonder/Base Components/Rendering Parameters/Footer
    */
    export type Footer =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/blueyonder/Base Components/Rendering Parameters/Footer
    */
    export type FooterJson =  {
        

    }
}
export namespace SiteSettings {

    /**
    * Represents the template /sitecore/templates/Feature/blueyonder/Site Settings/CDN Settings
    */
    export type CdnSettings =  {
        fields?: { 
            /**
            * Represents the cdnCss field (c16fc3f7-8201-4e4d-93ab-6b52dc5e3cf3).
            */
            cdnCss?: Field<string>;

            /**
            * Represents the cdnUrl field (6040f190-4f2b-4e0b-ac0e-9619caad0917).
            */
            cdnUrl?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/blueyonder/Site Settings/CDN Settings
    */
    export type CdnSettingsJson =  {
        
            /**
            * Represents the cdnCss field (c16fc3f7-8201-4e4d-93ab-6b52dc5e3cf3).
            */
            cdnCss?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the cdnUrl field (6040f190-4f2b-4e0b-ac0e-9619caad0917).
            */
            cdnUrl?: {
                jsonValue: Field<string>
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace BaseComponents.Footer.Constants {

    export const Footer = {
        TemplateId: "be825819-e2ea-4e2d-a00f-75ffaaeca1c8",
    
        BaseTemplateIds: [
            "5d7da26f-8d4b-4243-b25f-fdfea795f7a5", 
        ]
    }
    export const FooterFolder = {
        TemplateId: "8fdc1a9c-dc9d-4b04-a9c0-0a3abdede628",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace BaseComponents.Constants {

    export const Header = {
        TemplateId: "c381b5e8-b265-412c-8c6e-a46710a71b23",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace BaseComponents.Navigation.Constants {

    export const Link = {
        TemplateId: "b54b8fb4-81e5-424b-80c4-da847ce37933",
    
        BaseTemplateIds: [
            "0af677cb-7291-4fff-a324-a81383648bf3", 
        ]
    }
    export const LinkFolder = {
        TemplateId: "1256c3b2-aef8-46d8-9cd1-1097af29bf01",
    
        BaseTemplateIds: [
        ]
    }
    export const PrimaryFooterNavigation = {
        TemplateId: "ebe0a538-97c6-4b3b-868f-59a427b307e6",
    
        BaseTemplateIds: [
            "3683b1c1-1225-48d4-bc0b-28f0f73fd40c", 
        ]
    }
    export const SecondaryNavigation = {
        TemplateId: "ff569d64-3f86-4c36-b184-a1d467cc5778",
    
        BaseTemplateIds: [
        ]
    }
    export const SocialLink = {
        TemplateId: "a4c44abe-9e8a-4d52-b2d1-0d78337a8ad5",
    
        BaseTemplateIds: [
        ]
    }
    export const SocialLinkFolder = {
        TemplateId: "4e2c5d24-b802-4a6e-b8b4-a6bcd13266d4",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace BaseComponents.RenderingParameters.Constants {

    export const Footer = {
        TemplateId: "228d0343-ea21-4866-ab67-ba22b62e1abe",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace SiteSettings.Constants {

    export const CdnSettings = {
        TemplateId: "9a25e5df-b449-484c-9c3c-d3e03e7d6463",
    
        BaseTemplateIds: [
        ]
    }
}    


