
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { ItemEx, GqlItemEx } from './_.Sitecore.Override'
// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { ComponentProps } from '../lib/component-props';
// @ts-ignore 
import { BaseFields as FoundationBlueYonderBaseFields } from "./Foundation.BlueYonder.model"

export namespace BaseFields {

    /**
    * Represents the template /sitecore/templates/Foundation/blueyonder/Base Fields/_CTA
    */
    export type Cta =  {
        fields?: { 
            /**
            * Represents the CTA Link field (49af83d1-ad15-463e-8a7c-49f67dcbfa0d).
            */
            ctaLink?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/blueyonder/Base Fields/_CTA
    */
    export type CtaJson =  {
        
            /**
            * Represents the CTA Link field (49af83d1-ad15-463e-8a7c-49f67dcbfa0d).
            */
            ctaLink?: {
                jsonValue: LinkField
            };


    }

    /**
    * Represents the template /sitecore/templates/Foundation/blueyonder/Base Fields/_Logo
    */
    export type Logo =  {
        fields?: { 
            /**
            * Represents the Logo Image field (0f31a173-07e6-438b-bfe4-c24f2138c8bc).
            */
            logoImage?: ImageField;

            /**
            * Represents the Logo Url field (5c02333e-3f4c-4ddc-a086-646dcb4f2df3).
            */
            logoUrl?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/blueyonder/Base Fields/_Logo
    */
    export type LogoJson =  {
        
            /**
            * Represents the Logo Image field (0f31a173-07e6-438b-bfe4-c24f2138c8bc).
            */
            logoImage?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Logo Url field (5c02333e-3f4c-4ddc-a086-646dcb4f2df3).
            */
            logoUrl?: {
                jsonValue: LinkField
            };


    }

    /**
    * Represents the template /sitecore/templates/Foundation/blueyonder/Base Fields/_Primary Navigation
    */
    export type PrimaryNavigation =  {
        fields?: { 
            /**
            * Represents the Navigation Link field (a4cefef3-dcb5-4fb0-8299-9a1e5f74110f).
            */
            navigationLink?: LinkField;

            /**
            * Represents the Navigation Title field (90c50dec-ed13-4be1-8050-ef2da8838403).
            */
            navigationTitle?: Field<string>;

            /**
            * Represents the Secondary Navigations field (8ab49f36-dd90-4cce-bab7-d49dc5c2b9e5).
            */
            secondaryNavigations?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/blueyonder/Base Fields/_Primary Navigation
    */
    export type PrimaryNavigationJson =  {
        
            /**
            * Represents the Navigation Link field (a4cefef3-dcb5-4fb0-8299-9a1e5f74110f).
            */
            navigationLink?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Navigation Title field (90c50dec-ed13-4be1-8050-ef2da8838403).
            */
            navigationTitle?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Secondary Navigations field (8ab49f36-dd90-4cce-bab7-d49dc5c2b9e5).
            */
            secondaryNavigations?: {
                targetItems: any[]
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace BaseFields.Constants {

    export const Cta = {
        TemplateId: "0af677cb-7291-4fff-a324-a81383648bf3",
    
        BaseTemplateIds: [
        ]
    }
    export const Logo = {
        TemplateId: "5d7da26f-8d4b-4243-b25f-fdfea795f7a5",
    
        BaseTemplateIds: [
        ]
    }
    export const PrimaryNavigation = {
        TemplateId: "3683b1c1-1225-48d4-bc0b-28f0f73fd40c",
    
        BaseTemplateIds: [
        ]
    }
}    


