
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { ItemEx, GqlItemEx } from './_.Sitecore.Override'
// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { ComponentProps } from '../lib/component-props';
// @ts-ignore 
import { CorporatePages as ProjectBlueYonderCorporatePages } from "./Project.BlueYonder.model"
// @ts-ignore 
import { Project as ProjectBlueYonderProject } from "./Project.BlueYonder.model"

export namespace CorporatePages {

    /**
    * Represents the template /sitecore/templates/Project/blueyonder/Corporate Pages/Corporate Base Page
    */
    export type CorporateBasePage =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/blueyonder/Corporate Pages/Corporate Base Page
    */
    export type CorporateBasePageJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/blueyonder/Corporate Pages/Home Page
    */
    export type HomePage =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/blueyonder/Corporate Pages/Home Page
    */
    export type HomePageJson =  {
        

    }
}
export namespace Project.BlueYonder {

    /**
    * Represents the template /sitecore/templates/Project/blueyonder/Headless Site
    */
    export type HeadlessSite =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/blueyonder/Headless Site
    */
    export type HeadlessSiteJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/blueyonder/Headless Tenant
    */
    export type HeadlessTenant =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/blueyonder/Headless Tenant
    */
    export type HeadlessTenantJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/blueyonder/JSS Settings
    */
    export type JssSettings =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/blueyonder/JSS Settings
    */
    export type JssSettingsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/blueyonder/Page
    */
    export type Page =  {
        fields?: { 
            /**
            * Represents the Content field (00543c90-de99-454f-8aca-a3addd08cc0f).
            */
            Content?: Field<string>;

            /**
            * Represents the Title field (ed506a36-c56e-4506-b142-9c5e266cbd39).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/blueyonder/Page
    */
    export type PageJson =  {
        
            /**
            * Represents the Content field (00543c90-de99-454f-8aca-a3addd08cc0f).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (ed506a36-c56e-4506-b142-9c5e266cbd39).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/blueyonder/Page Design Folder
    */
    export type PageDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/blueyonder/Page Design Folder
    */
    export type PageDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/blueyonder/Page Designs
    */
    export type PageDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/blueyonder/Page Designs
    */
    export type PageDesignsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/blueyonder/Partial Design Folder
    */
    export type PartialDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/blueyonder/Partial Design Folder
    */
    export type PartialDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/blueyonder/Partial Designs
    */
    export type PartialDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/blueyonder/Partial Designs
    */
    export type PartialDesignsJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace CorporatePages.Constants {

    export const CorporateBasePage = {
        TemplateId: "046fd747-ae14-4480-9821-540724bb57ec",
    
        BaseTemplateIds: [
        ]
    }
    export const HomePage = {
        TemplateId: "5fee350b-5cd8-467b-93d9-33a60b461b44",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Project.BlueYonder.Constants {

    export const HeadlessSite = {
        TemplateId: "e59a3221-0b86-46ce-9608-49e2ddc87a3d",
    
        BaseTemplateIds: [
        ]
    }
    export const HeadlessTenant = {
        TemplateId: "424044bd-56e5-4d86-9f1e-743923166f04",
    
        BaseTemplateIds: [
        ]
    }
    export const JssSettings = {
        TemplateId: "2ee1fc9d-056c-480f-bd03-444804d56ba6",
    
        BaseTemplateIds: [
        ]
    }
    export const Page = {
        TemplateId: "7518e3d2-b740-46a0-92c7-9e267e7e1aaf",
    
        BaseTemplateIds: [
        ]
    }
    export const PageDesignFolder = {
        TemplateId: "9938ce94-81da-47cb-9c95-df6e14df41b0",
    
        BaseTemplateIds: [
        ]
    }
    export const PageDesigns = {
        TemplateId: "99d802a3-2e9b-402d-a720-baec9b26ae3a",
    
        BaseTemplateIds: [
        ]
    }
    export const PartialDesignFolder = {
        TemplateId: "fc6f3c19-e94a-4677-932f-73a87bdeda86",
    
        BaseTemplateIds: [
        ]
    }
    export const PartialDesigns = {
        TemplateId: "7d4c5190-6611-4957-bc42-e89fd93802b9",
    
        BaseTemplateIds: [
        ]
    }
}    


